FROM mysql:9.5.0


LABEL org.opencontainers.image.source=https://github.com/u2waremanager/io.u2ware.examples.environment
LABEL org.opencontainers.image.description="MySQL 9.5.0 with common environment settings for U2ware"
