FROM postgres:16.4-alpine3.20

LABEL org.opencontainers.image.source=https://github.com/u2waremanager/io.u2ware.examples.environment
LABEL org.opencontainers.image.description="Postgres 9.5.0 with common environment settings for U2ware"
